// src/types/database.ts
// Database types - Update these based on your Supabase schema
// This is a placeholder - will be generated by Supabase CLI

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          user_type: 'freelancer' | 'client' | 'both';
          is_premium: boolean;
          phone_number: string | null;
          country: string | null;
          city: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          user_type?: 'freelancer' | 'client' | 'both';
          is_premium?: boolean;
          phone_number?: string | null;
          country?: string | null;
          city?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          user_type?: 'freelancer' | 'client' | 'both';
          is_premium?: boolean;
          phone_number?: string | null;
          country?: string | null;
          city?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      gigs: {
        Row: {
          id: string;
          freelancer_id: string;
          title: string;
          description: string;
          category_id: string | null;
          price: number;
          delivery_time_days: number;
          images: string[];
          tags: string[];
          status: 'active' | 'paused' | 'deleted';
          views: number;
          orders_count: number;
          rating: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          freelancer_id: string;
          title: string;
          description: string;
          category_id?: string | null;
          price: number;
          delivery_time_days: number;
          images?: string[];
          tags?: string[];
          status?: 'active' | 'paused' | 'deleted';
          views?: number;
          orders_count?: number;
          rating?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          freelancer_id?: string;
          title?: string;
          description?: string;
          category_id?: string | null;
          price?: number;
          delivery_time_days?: number;
          images?: string[];
          tags?: string[];
          status?: 'active' | 'paused' | 'deleted';
          views?: number;
          orders_count?: number;
          rating?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          gig_id: string | null;
          client_id: string;
          freelancer_id: string;
          status:
            | 'pending'
            | 'in_progress'
            | 'delivered'
            | 'completed'
            | 'cancelled'
            | 'disputed';
          amount: number;
          platform_fee: number;
          payment_status: 'pending' | 'held' | 'released' | 'refunded';
          payment_method: string | null;
          payment_id: string | null;
          delivery_date: string | null;
          requirements: string | null;
          deliverables: string | null;
          created_at: string;
          updated_at: string;
        };
      };
      marketplace_items: {
        Row: {
          id: string;
          seller_id: string;
          title: string;
          description: string;
          category_id: string | null;
          price: number;
          images: string[];
          stock_quantity: number;
          condition: 'new' | 'like_new' | 'used' | 'refurbished' | null;
          status: 'active' | 'sold' | 'inactive';
          views: number;
          created_at: string;
          updated_at: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          icon: string | null;
          type: 'gig' | 'marketplace' | 'both';
          created_at: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

// src/types/index.ts
// Application types

export interface User {
  id: string;
  email: string;
  fullName: string | null;
  avatarUrl: string | null;
  bio: string | null;
  userType: 'freelancer' | 'client' | 'both';
  isPremium: boolean;
  createdAt: string;
}

export interface Gig {
  id: string;
  freelancerId: string;
  title: string;
  description: string;
  categoryId: string | null;
  price: number;
  deliveryTimeDays: number;
  images: string[];
  tags: string[];
  status: 'active' | 'paused' | 'deleted';
  views: number;
  ordersCount: number;
  rating: number;
  createdAt: string;
  updatedAt: string;
  freelancer?: User;
}

export interface Order {
  id: string;
  orderNumber: string;
  gigId: string | null;
  clientId: string;
  freelancerId: string;
  status:
    | 'pending'
    | 'in_progress'
    | 'delivered'
    | 'completed'
    | 'cancelled'
    | 'disputed';
  amount: number;
  platformFee: number;
  paymentStatus: 'pending' | 'held' | 'released' | 'refunded';
  paymentMethod: string | null;
  paymentId: string | null;
  deliveryDate: string | null;
  requirements: string | null;
  deliverables: string | null;
  createdAt: string;
  updatedAt: string;
  gig?: Gig;
  client?: User;
  freelancer?: User;
}

export interface MarketplaceItem {
  id: string;
  sellerId: string;
  title: string;
  description: string;
  categoryId: string | null;
  price: number;
  images: string[];
  stockQuantity: number;
  condition: 'new' | 'like_new' | 'used' | 'refurbished' | null;
  status: 'active' | 'sold' | 'inactive';
  views: number;
  createdAt: string;
  updatedAt: string;
  seller?: User;
}

export interface Category {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  icon: string | null;
  type: 'gig' | 'marketplace' | 'both';
  createdAt: string;
}

export interface ApiResponse<T> {
  data?: T;
  error?: string;
  message?: string;
}
